/**
 * Decompile / recompile a Dofus 1.29 lang SWF, entirely in JavaScript.
 *
 * Pipeline:
 *
 *   SWF bytes
 *     │
 *     ▼  readSWF()  (lib/swf-format.js)
 *   { signature, version, frameSize, frameRate, frameCount, tags }
 *     │
 *     ▼  decodeActions() + runVM()  (lib/as2-vm.js)
 *   { FILE_BEGIN, VERSION, A, FILE_END, … }  — the lang data tree
 *
 * The reverse path takes a (possibly edited) data tree, calls `emitData()` to
 * produce a fresh action stream, encodes it back into a single DoAction tag,
 * replaces the original DoAction tag(s), then writeSWF()-s a new file.
 *
 * For the human-readable AS2 textarea on the web UI we still go through the
 * existing `parser.js` / `serializer.js`: the data tree is converted to
 * pseudo-AS2 source, and on save the source is re-parsed back to a tree
 * before being passed to `recompile()`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { Buffer } from 'node:buffer';
import { readSWF, writeSWF, TAG_DO_ACTION } from './swf-format.js';
import { decodeActions, runVM, emitData, encodeActions } from './as2-vm.js';
import { serializeAS2 } from './parser.js';

export function getFFDecPath() {
  // Kept for backwards compatibility with the /api/status endpoint. The new
  // implementation does not need FFDec at all.
  return null;
}

function rmrf(p) {
  if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true });
}

function readDataFromBuffer(buffer) {
  const swf = readSWF(buffer);
  const bodies = swf.tags.filter((t) => t.code === TAG_DO_ACTION).map((t) => t.body);
  if (bodies.length === 0) {
    throw new Error('SWF contains no DoAction tag');
  }
  const combined = Buffer.concat(bodies);
  const actions = decodeActions(combined);
  return { swf, data: runVM(actions) };
}

function writeDataToBuffer(swf, data) {
  const { actions } = emitData(data);
  const body = encodeActions(actions);
  const newTags = [];
  let inserted = false;
  for (const t of swf.tags) {
    if (t.code === TAG_DO_ACTION) {
      if (!inserted) {
        newTags.push({ code: TAG_DO_ACTION, body });
        inserted = true;
      }
      // Drop additional DoAction tags — everything is merged into one.
    } else {
      newTags.push(t);
    }
  }
  if (!inserted) {
    // Should not happen for our files, but be defensive.
    const tail = newTags.pop(); // assume END tag
    newTags.push({ code: TAG_DO_ACTION, body });
    if (tail) newTags.push(tail);
  }
  return writeSWF({ ...swf, tags: newTags });
}

export async function decompile(swfPath, cacheDir) {
  // No on-disk caching. Read+decode+serialize is ~100 ms for the biggest
  // file, which is fast enough for the interactive UI and removes the risk of
  // serving a stale source generated by an older serializer version.
  const buffer = fs.readFileSync(swfPath);
  const { data } = readDataFromBuffer(buffer);
  const source = serializeAS2(data);
  return { source, data };
}

export async function recompile(swfPath, cacheDir, newSource, options = {}) {
  let data = options.data;
  if (!data) {
    const { parseAS2 } = await import('./parser.js');
    data = parseAS2(newSource);
  }

  const originalBuffer = fs.readFileSync(swfPath);
  const { swf } = readDataFromBuffer(originalBuffer);
  const rebuilt = writeDataToBuffer(swf, data);

  const backupPath = `${swfPath}.bak`;
  if (!fs.existsSync(backupPath)) {
    fs.copyFileSync(swfPath, backupPath);
  }
  fs.writeFileSync(swfPath, rebuilt);

  return { swfPath, backupPath };
}
